### ISSUE TITLE
[new feature request]support docker 

### ISSUE THREAD

**Issue by tuhaolam** [NZTA/SDLT#19]
Hi, can you append a new type to install? Maybe using docker is a better choise! 
Thanks a lot.

**Comment by Zaita** [comment]
Currently a pull request to add this support :)

**Comment by Zaita** [comment]
This has been merged into the branch branch.

git clone .
cp .env.example .env
docker-compose up -d

Note: It will take a few minutes for the PHP container to fully start. You can use docker logs -f to watch for it to complete.

Then http://localhost:666/
