### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by lani-cybertoa** [NZTA/SDLT#23]
Hi, 

I am getting a 404 error when trying to launch silverstripe. 

I setup a LAMP environment with phpmyadmin and apache.
Attached are sceenshots of my current .env silverstripe file and the error im getting. I think it has something to do with my env configuration file but I'm not 100% sure.

Any help much appreciated.

![404error](https://user-images.githubusercontent.com/58314342/82850531-e700a280-9f50-11ea-996f-6f3429714d22.png)
![envfile](https://user-images.githubusercontent.com/58314342/82850533-e831cf80-9f50-11ea-9a6a-ea490530e927.png)

**Comment by Zaita** [comment]
Hi Lani,
Did you follow the guide at:
https://github.com/NZTA/SDLT/wiki/Installation-Setup-Apache ?

If so, can you post a screenshot of your browser development console network tab with the 404 error displayed? (Ctrl+Shift+E in Firefox, Ctrl+Shift+i in Chrome)

**Comment by lani-cybertoa** [comment]
I did not follow that guide but the one I followed was very similiar. Will give this guide a try as well. 

This is the error here:
![image](https://user-images.githubusercontent.com/58314342/82856346-d9074d80-9f61-11ea-86b7-33da492c42cf.png)

**Comment by elliot-sawyer** [comment]
Looks like you're nearly there. The server appears to be running, the database is not throwing any errors, and you've got a compiled theme. A few things to check:
1) What is your document root for Apache - does it end with /public?
2) Is `mod_rewrite` enabled?
3) Have you run `composer install` on the CLI? If the graphql endpoint 404's, the module may be missing.
4) Have you run  `https://whatever.host/dev/build?flush=` or `vendor/bin/sake dev/build flush=` on the CLI?

**Comment by lani-cybertoa** [comment]
> 
> 
> Looks like you're nearly there. The server appears to be running, the database is not throwing any errors, and you've got a compiled theme. A few things to check:
> 
>     1. What is your document root for Apache - does it end with /public?
> 
>     2. Is `mod_rewrite` enabled?
> 
>     3. Have you run `composer install` on the CLI? If the graphql endpoint 404's, the module may be missing.
> 
>     4. Have you run  `https://whatever.host/dev/build?flush=` or `vendor/bin/sake dev/build flush=` on the CLI?

**Comment by lani-cybertoa** [comment]
Hey,

SOLVED THANKYOU !!

I just had to enable and load the apache rewrite module :)
