### ISSUE TITLE
Restarting docker container (PHP) overwrites local question changes with baseline

### ISSUE THREAD

**Issue by Zaita** [NZTA/SDLT#30]
The lines in the setup_php file:
/var/www/html/vendor/bin/sake dev/tasks/HydrateCustomConfig
/var/www/html/vendor/bin/sake dev/tasks/SetupSDLTDataTask

Will overwrite any changes to the baseline.

**Comment by elliot-sawyer** [comment]
SetupSDLTDataTask should only be used for the initial setup. It will create a new question, or find an existing question with the same name and update the data.

Is there a way to pass a flag or argument into the Docker container to skip that command? Or only run if the flag is present?
